# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Photo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Photo
  pod 'Alamofire'
  pod 'SDWebImage'
  pod 'SnapKit', '~> 5.0.0'
  
  target 'PhotoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PhotoUITests' do
    # Pods for testing
  end

end
